### ISSUE TITLE
Issues creating Circos input

### ISSUE THREAD

**Issue by thorellk** [tipputa/circular-visualization#1]
Dear Dr. Tada,

Thank you for a really nice publication in BMC Genomics and for sharing the code here at GitHub! I managed to install the software with all dependencies and ran it successfully with the test dataset that was contained in the repository. However, when I run it on my dataset of 24 complete PacBio genomes the software fails. The blast steps finishes without any issues, both the first and second alignment round but after that I get the following error:

```
Create Circos input (./circos/data/).
NQ4056_chr, start bp: 12, End bp: 1665022, Number of visualized genes: 1536, Number of removal genes: 9
Traceback (most recent call last):
  File "/home/kaisa/tools/Circular-genome-visualizer/bin/runAllProcess.py", line 51, in <module>
    createCircos.runs(df, timeRecorder, RootDir, gbDir)
  File "/pica/h1/kaisa/tools/Circular-genome-visualizer/bin/createCircos.py", line 379, in runs
    run.createCircosInput2(df_locusTag, "unaligned", consensus_gsize, CircosIN, df_info)
  File "/pica/h1/kaisa/tools/Circular-genome-visualizer/bin/createCircos.py", line 291, in createCircosInput2
    tmp.to_csv(file_name, sep = "\t",header=None, index=None)
  File "/proj/b2016371/anaconda3/lib/python3.5/site-packages/pandas/core/frame.py", line 1344, in to_csv
    formatter.save()
  File "/proj/b2016371/anaconda3/lib/python3.5/site-packages/pandas/formats/format.py", line 1526, in save
    compression=self.compression)
  File "/proj/b2016371/anaconda3/lib/python3.5/site-packages/pandas/io/common.py", line 424, in _get_handle
    f = open(path, mode, errors='replace')
FileNotFoundError: [Errno 2] No such file or directory: 'output/circos/data/circos_unaligned_NQ4056_chr.txt'
```
Checking the circos/data directory there are \*.original.txt files for each file but no circos_unaligned\* files. Do you recognize this error and do you have any suggestions on how to solve it?

Best regards,
Kaisa

[Genome_viz_NQ_170421.txt](https://github.com/tipputa/Circular-genome-visualizer/files/947426/Genome_viz_NQ_170421.txt)

**Comment by tipputa** [comment]
Thank you for your issue report. I guess that you are using a relative path for an output directory. This program requires an absolute path.
Please try the following command:
```sh
python /home/kaisa/tools/Circular-genome-visualizer/bin/runAllProcess.py /pica/v8/b2017024_nobackup/Camargo/NQ_Vanderbilt/Rearrangements/output /pica/v8/b2017024_nobackup/Camargo/NQ_Vanderbilt/Rearrangements/genbank/
```
or, if you have BLAST result files, you can use runAfterBlastProcess.py instead of runAllProcess.py.
```sh
python /home/kaisa/tools/Circular-genome-visualizer/bin/runAfterBlastProcess.py /pica/v8/b2017024_nobackup/Camargo/NQ_Vanderbilt/Rearrangements/output /pica/v8/b2017024_nobackup/Camargo/NQ_Vanderbilt/Rearrangements/genbank/
```

Best regards,
Ipputa Tada

**Comment by thorellk** [comment]
Thank you for your fast reply. Setting the absolute path did the trick and the analysis finished succesfully. 

Best wishes,
Kaisa
