### ISSUE TITLE
Error during runAllProcess.py

### ISSUE THREAD

**Issue by BiocD** [tipputa/circular-visualization#3]
Dear tipputa,

thank you for sharing your code, I'm really interested on it. 
Running your code whitin a dataset of 4 genomes, during the parsing of BLAST outputs, I found the following error, probably related to pandas:

3. Parsing BLAST output
/home/david/Binaries/Circular-genome-visualizer/bin/createOrthologousGenes.py:117: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  DL.to_csv(self.blastResultDir + pivot + "_locusTag.tsv", sep="\t", na_rep='-',index= None)
Traceback (most recent call last):
  File "/home/david/Binaries/Circular-genome-visualizer/bin/runAllProcess.py", line 37, in <module>
    createOrtho.runs(timeRecorder, RootDir, gbDir)
  File "/home/david/Binaries/Circular-genome-visualizer/bin/createOrthologousGenes.py", line 165, in runs
    dfs=run.makeTable(acc)
  File "/home/david/Binaries/Circular-genome-visualizer/bin/createOrthologousGenes.py", line 130, in makeTable
    output = out.drop_duplicates()
  File "/home/david/miniconda2/envs/Circular/lib/python3.6/site-packages/pandas/core/frame.py", line 4630, in drop_duplicates
    duplicated = self.duplicated(subset, keep=keep)
  File "/home/david/miniconda2/envs/Circular/lib/python3.6/site-packages/pandas/core/frame.py", line 4687, in duplicated
    labels, shape = map(list, zip(*map(f, vals)))
  File "/home/david/miniconda2/envs/Circular/lib/python3.6/site-packages/pandas/core/frame.py", line 4668, in f
    vals, size_hint=min(len(self), _SIZE_HINT_LIMIT))
  File "/home/david/miniconda2/envs/Circular/lib/python3.6/site-packages/pandas/util/_decorators.py", line 188, in wrapper
    return func(*args, **kwargs)
  File "/home/david/miniconda2/envs/Circular/lib/python3.6/site-packages/pandas/core/algorithms.py", line 613, in factorize
    na_value=na_value)
  File "/home/david/miniconda2/envs/Circular/lib/python3.6/site-packages/pandas/core/algorithms.py", line 460, in _factorize_array
    na_value=na_value)
  File "pandas/_libs/hashtable_class_helper.pxi", line 1792, in pandas._libs.hashtable.PyObjectHashTable.factorize
  File "pandas/_libs/hashtable_class_helper.pxi", line 1712, in pandas._libs.hashtable.PyObjectHashTable._unique
TypeError: unhashable type: 'list'

No circos ouputs were generated. Any ideas or suggestions to solve this problem?
Regards,
David

**Comment by tipputa** [comment]
Dear David,

Thank you very much for your interest! 
I tried it using some different datasets but I was not able to replicate that bug.

Regarding the error message, I think the reason is that the locusTag.tsv files, which are <output folder>/BlastResult/<AccessionNo>_locusTag.tsv, include some blankets [].
But I do not know why and how you can solve it...

If you can send me your GenBank files (if they are already released) by WeTransfer (https://wetransfer.com/) or something, I will check it and fix my program.
My email address is tipputa@nig.ac.jp

Best regards,
tIpputa

**Comment by BiocD** [comment]
Thank you so much for your fastest response.
I've downloaded some Streptococcus mitis Gb files from Gene Bank.
Unfortunetly I'm no longer at my workstation... If is not a problem I can
send you Gb files on Monday.

Regards,
Davis

Il giorno ven 29 mar 2019, 17:21 tipputa <notifications@github.com> ha
scritto:
